// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_this_is_a_touchscreen = "CgkI9fGT-7MIEAIQCg"; // <GPGSID>
        public const string achievement_overdrive = "CgkI9fGT-7MIEAIQDA"; // <GPGSID>
        public const string achievement_could_have_read_a_book = "CgkI9fGT-7MIEAIQAw"; // <GPGSID>
        public const string achievement_triple_digit_blunder = "CgkI9fGT-7MIEAIQDQ"; // <GPGSID>
        public const string achievement_i_could_have_gone_pro = "CgkI9fGT-7MIEAIQBw"; // <GPGSID>
        public const string achievement_time_catches_us_all = "CgkI9fGT-7MIEAIQCw"; // <GPGSID>
        public const string achievement_im_kind_of_a_big_deal = "CgkI9fGT-7MIEAIQCA"; // <GPGSID>
        public const string achievement_first_of_many = "CgkI9fGT-7MIEAIQBA"; // <GPGSID>
        public const string leaderboard_final_score = "CgkI9fGT-7MIEAIQDg"; // <GPGSID>
        public const string achievement_oops = "CgkI9fGT-7MIEAIQCQ"; // <GPGSID>
        public const string achievement_wasnt_that_busy = "CgkI9fGT-7MIEAIQAA"; // <GPGSID>
        public const string achievement_that_queue_was_crazy = "CgkI9fGT-7MIEAIQAg"; // <GPGSID>
        public const string achievement_hold_my_drink_ill_be_right_back = "CgkI9fGT-7MIEAIQBg"; // <GPGSID>
        public const string achievement_a_bit_of_a_queue = "CgkI9fGT-7MIEAIQAQ"; // <GPGSID>
        public const string achievement_getting_the_hang_of_this_now = "CgkI9fGT-7MIEAIQBQ"; // <GPGSID>

}

